name: Build and Deploy to EC2 Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -f dockerfile -t jaaz-cloud:dev .

      - name: Save Docker image to tar file
        run: |
          docker save jaaz-cloud:dev -o jaaz-cloud-dev.tar
          gzip jaaz-cloud-dev.tar

      - name: Transfer Docker image to EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "jaaz-cloud-dev.tar.gz"
          target: "/tmp/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Load the Docker image from tar file
            cd /tmp
            gunzip jaaz-cloud-dev.tar.gz
            docker load -i jaaz-cloud-dev.tar

            # Stop and remove existing container
            docker stop jaaz-cloud-dev || true
            docker rm jaaz-cloud-dev || true

            # Run new container
            docker run -d \
              --name jaaz-cloud-dev \
              --restart unless-stopped \
              -p 3000:3000 \
              --env-file ~/.env.dev \
              jaaz-cloud:dev

            # Clean up
            rm -f /tmp/jaaz-cloud-dev.tar
            docker image prune -f
